<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cb53403a-71a6-41b2-b916-4e9f9d77070f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.mars-logo-row__at-right .cart-header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cart-header cart-header_empty')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-header cart-header_empty</value>
        <webElementGuid>148b5ca8-8404-4287-be8f-e854aa78fb12</webElementGuid>
    </webElementProperties>
</WebElementEntity>